
(* The External Language *)

structure EL =
struct

  type intconst = Word32.word
  type priority = string
  type prio = string (* FIX: delete this *)
  (* FIX: constraints *)
  type pconstraint = prio * prio (* priority constraints *)
  (* datatype pconstraint = 
      PCAnd of pconstraint * pconstraint
    | PCOr of pconstraint * pconstraint
    | PCLessEqual of exp * exp
    | PCEqual of exp * exp *)
  type rfmt = string
  type psconstraint = unit (* XXX *)
  type id = string

  datatype longid =
      Id of id
    | Path of id * longid
  
(*
      PrVar of string
    | PrConst of priority
*)

  datatype exp_ =

      Constant of constant
    | Var of longid
    | Float of real

    | App of exp * exp * bool (* infix? *)

    | LabeledArg of string * exp (* only for OCaml backend *)

    | Let of dec * exp

    | Record of (string * exp) list
    (* vector constructor *)
    | Vector of exp list
    (* #label/typ exp *)
    | Proj of string * typ * exp

    | Andalso of exp * exp
    | Orelse of exp * exp
    | Andthen of exp * exp
    | Otherwise of exp * exp
    | If of exp * exp * exp

    | Primapp of string * typ list * exp list

    | Seq of exp * exp
    | Constrain of exp * typ

    (* same as concat, maybe worth making efficient *)
    (* | Jointext of exp list *)

    | Raise of exp

    (* optional delayed default can only be generated by the compiler *)
    | Case of exp list * (pat list * exp) list * (unit -> exp) option

    (* compile-time warning if this code is live *)
    | CompileWarn of string

    | ECmd of cmd_ (* FIX: ECmd of cmd_ *)
    (* | PFn of ppat list * pat list * exp (* priority abstraction *) (* FIX: delete this *) *)
    (* | PApply of exp * prio (* FIX: delete this *) *)

    | Handle of exp * (pat * exp) list

    (* priority ceiling needs to be annotated for now *)
    | NewMutex of exp

  and cmd_ =
      IBind of ((string * exp) list) * exp
    | Spawn of exp * cmd  (* Spawn of exp * cmd *)
    | Sync of exp
    | Poll of exp
    | Cancel of exp
    | IRet of exp
    | Change of exp  (* Change of exp *)
    | WithMutex of exp * cmd (* mutex, critical section *)

  and constant =
      CInt of intconst
    | CString of string
    | CChar of char
    | CPrio of priority

  and pat = (* any pattern *)
      PVar of string
    | PWild (* "_" (matches anything) *)
    | PAs of string * pat (* "as" syntax for matching *)
    | PRecord of (string * pat) list (* record matching *)
    | PConstrain of pat * typ
    | PConstant of constant
    | PApp of string * pat option (* matching on constructors *)
    | PWhen of exp * pat (* "when" syntax for matching *)

(*  and pconstraint =
      CLess of prio * prio
    | CAnd of pconstraint * pconstraint
 *)

  and ppat = (* fn[p] pattern *) (* FIX: delete this *)
      PPVar of string
    | PPConstrain of string * pconstraint list (* pconstraint *)

  and typ =
      TVar of string
    | TApp of typ list * string
    | TRec of (string * typ) list
(*    | TSham of string option * typ
    | TAt of typ * world *)
    | TArrow of typ * typ (* FIX: TArrow of (string * typ) * typ *)
    (* shortcut for tuple length *)
    | TNum of int
  (*     | TAddr of world (* can only be the address of a world expression *) *)
    (* Fix: 3 refinements for cmds *)
    (* | TCmd of typ * (rfmt * rfmt * rfmt) *)
    | TCmd of typ * rfmt
    | TThread of typ * rfmt
    (* | TForall of ppat * typ (* FIX: delete this *) *) 

    | TPrio of rfmt

    | TMutex of rfmt

  and dec_ =
      (* wish we had refinements here. 
         val pat cannot contain PConstant or PApp *)
      (* val (a, b) loop = Util.loop : a -> b *)
      Val of string list * pat * exp
    | SigVal of string * typ
    | Do of exp
    | Type of string list * string * typ
    | SigType of string list * string

    (* fun (a, b, c) f p1 p2 p3 : t1 = e1
         |           f p1 p2 p3 : t2 = e2
       and g p1 p2 : t3 = e3
         | ... *)
    | Fun of { inline : bool,
               funs : (string list * string * 
                       (pat list * typ option * exp) list) list }

    (* | WFun of string * ppat list * pat list * typ option * exp (* FIX: delete this *) *)

    (* datatype (a, b, c) t = A of t | B of b | C of t1
       and                u = D of u | E of t *)
    | Datatype of string list * 
                  (string * (string * typ option) list) list
    | Tagtype of string
      (* newtag Fail (valid?) of string in exn *)
    | Newtag of string * typ option * string
      (* just means newtag E of TO in "exn" *)
    | Exception of string * typ option

    (* extern val (a, b) loop : a -> b
     *)
    | ExternVal of string list * string * typ
    | ExternType of string list * string

    | Structure of string * dec list
    | Signature of string * dec list

				
  and tdec =
      Dec of dec
    | Priority of string
    | Order of string * string
    | Fairness of string * intconst

  and prog =
      Prog of tdec list * cmd
  (* fixity decls are handled at parse time *)

(*
  and elunit =
    Unit of dec list * export list

  and export =
    (* in the case that the export is not supplied, 
       we assume the identifier also used for export *)
    ExportType of string list * string * typ option
  | ExportVal of string list * string * exp option

*)

  withtype exp = exp_ * Pos.pos
  and dec = dec_ * Pos.pos
  and cmd = cmd_ * Pos.pos

end
